name: Deploy to Docker & Render on Production Push

on:
  push:
    branches: ["production"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t yi1907/pizza-shop-deploy:latest .

      - name: Push Docker image
        run: docker push yi1907/pizza-shop-deploy:latest

      - name: Trigger Render deployment
        run: |
          curl -X POST "${{ secrets.API_RENDER_DEPLOY }}"
